package com.transfolio.transfolio.dto;

import lombok.Data;

@Data
public class TransferRumorDTO {
    private String id;
    private String playerID;
    private String fromClubID;
    private String toClubID;
    private boolean closed;
    private String probability;
    private String progression;
    private String threadUrl;
    private String lang;
    private long lastPostDate;
    private String closedType;
    private long marketValue;
    private String currency;

    private String summary; // fan-style summary generated by Gemini
}
